# POST http://localhost:8080/ai-agent
# Content-Type: application/json

# {"prompt": "what i asked previously?", "stream": false, "sessionId": "session_1748375240294690000"}

# {
#     "messages": [
#       { "role": "system", "content": "You are a witty AI assistant." },
#       { "role": "user", "content": "Tell me a programming joke." }
#     ]
# }

# {
#   "count": 3,
#   "sessions": [
#     "session_1748374904593657000",
#     "session_1748364691636229000",
#     "session_1748364639113274000"
#   ]
# session_1748369133911470000

# GET  http://localhost:8080/sessions
# Content-Type: application/json

# GET http://localhost:8080/stats
# Content-Type: application/json

GET http://localhost:8080/session/test-session-001
Content-Type: application/json